theme = "my-onedark"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
scrolloff = 6
scroll-lines = 3
mouse = true
middle-click-paste = true
shell = [ "sh", "-c" ]
line-number = "relative"
cursorline = true
cursorcolumn = false
gutters = [ "diff", "line-numbers", "spacer", ]
auto-completion = true
auto-format = false
rulers = [120]
auto-save = true
idle-timeout = 0
completion-trigger-len = 2
auto-info = true
true-color = true
bufferline = "always"
color-modes = true
auto-pairs = true
soft-wrap.enable = true

[editor.statusline]
separator = "|"
mode.normal = "NORMAL"
mode.select = "SELECT"
mode.insert = "INSERT"

left = [ "mode", "file-name", "separator", "spacer", "version-control", "spacer", "separator", "spacer", "diagnostics", ]
center = []
right = [ "position", "separator",  "spacer", "position-percentage", "spacer", "separator",  "total-line-numbers", "separator",  "file-line-ending", "separator",  "file-type", ]

[editor.lsp]
display-messages = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
# space = "·"
nbsp = "⍽"
# tab = "→"
newline = "⏎"
# tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "│"
skip-levels = 0

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
"%" = "match_brackets"
V = ["select_mode", "extend_to_line_bounds"]
G = "goto_file_end"

# Search for word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

[keys.insert]
C-h = "move_char_left"
C-j = "move_line_down"
C-k = "move_line_up"
C-l = "move_char_right"

[keys.select]
G = "goto_file_end"

# Visual-mode specific muscle memory
i = "select_textobject_inner"
a = "select_textobject_around"
