inherits = "onedark"

"diagnostic.error" = { underline = { style = "curl", color = "red" } }
"ui.cursorline.primary" = { underline = { color = "white", style = "double_line" } }
"ui.cursorline.secondary" = { underline = { color = "white", style = "line" } }
