[ids]                                                                                                                                                                                                                                                 

*                                                                                                                                                                                                                                                     
																													      
[main]

capslock = timeout(C-space, 500, capslock)


